name: airframes_aggregation_server
version: 0.2.3
environment:
  sdk: '>=2.9.0 <3.0.0'
dependencies:
  args: ^1.6.0
  angel_orm: ^2.0.2
  angel_orm_postgres: ^1.0.0
<<<<<<< HEAD
  convert: ^2.1.1
=======
  convert:
  dartis: ^0.5.0
>>>>>>> last-good
  json_annotation: ^3.0.1
  nats:
    git: https://github.com/c16a/nats-dart.git
  quick_log: ^0.4.0
<<<<<<< HEAD
  udp: ^3.0.3
dev_dependencies:
  angel_orm_generator: ^2.0.5
  build_runner: ^1.9.0
  json_serializable: ^3.3.0
=======
  udp: ^3.0.2
  # dart_json_mapper: ^1.5.20
  async: ^2.2.0
  grpc: 2.2.0
  protobuf: ^1.0.1
  dart_express: ^0.5.3
dev_dependencies:
  angel_orm_generator: ^2.0.5
  build_runner: ^1.7.3
  json_serializable: ^3.2.5
dependency_overrides:
  analyzer: 0.39.10
  angel_model: 1.0.3
  angel_orm: 2.0.2
  angel_orm_generator: 2.0.5
  angel_orm_postgres: 1.0.0
  angel_serialize: 2.2.3+3
  angel_serialize_generator: 2.5.0
  async: 2.4.0
  build: 1.3.0
  build_config: 0.4.2
  build_daemon: 2.1.2
  build_resolvers: 1.3.9
  build_runner: 1.10.0
  build_runner_core: 5.2.0
  dart_style: 1.3.3
  grpc: 2.2.0
  http_multi_server: 2.2.0
  json_serializable: 3.2.5
  postgres: 2.1.1
  reflectable: 2.2.5
  source_gen: 0.9.4+6
>>>>>>> last-good
